### ISSUE TITLE
Pb with lib go-ldap v3: Call using int64 as type string

### ISSUE THREAD

**Issue by djacomy** [wiltonsr/ldapAuth#37]
I try to install middleware ldapAuth v0.0.21 whith traefik 2.9.8n but I get this error just after connecting to the ldap

time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/**request.go:50:2**: panic" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth

```
func (l *Conn) readPacket(msgCtx *messageContext) (*ber.Packet, error) {
	l.Debug.Printf("**%d**: waiting for response", msgCtx.id)`

msgCtx.id is a string, but waited en integer


time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/bind.go:61:5: panic" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth

time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/bind.go:100:3: panic" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth

time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/ldapauth.go:232:5: panic" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth

time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/ldapauth.go:125:6: panic" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth

time="2023-03-17T12:44:34Z" level=error msg="Recovered from panic in HTTP handler [192.168.32.1:59358 - /]: reflect: **Call using int64 as type string**" middlewareName=traefik-internal-recovery middlewareType=Recovery


time="2023-03-17T12:44:34Z" level=error msg="Stack: goroutine 138 [running]:\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x52e0cb0, 0xc000efd410}, 0xc001b27e00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x225\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc001f71690})\n\truntime/panic.go:884 +0x212\nreflect.Value.call({0x3b06380?, 0xc001a17890?, 0xc0016ae7e0?}, {0x472a1fe, 0x4}, {0xc001a178c0, 0x2, 0xc0012c9988?})\n\treflect/value.go:440 +0x1abf\nreflect.Value.Call({0x3b06380?, 0xc001a17890?, 0xc001efd900?}, {0xc001a178c0?, 0xc0012c9988?, 0x196?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc001a178c0?, 0xc001a17890?, 0xc001533c00?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0026aafd0)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc001efa280, 0xc0026aafd0, 0x2?, 0xc001b95b80?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc0026952c0, 0x1, 0x1?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0xc001df3740?, 0xc001a150b0?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc0026952a8, 0x1, 0xc00229aa90?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc001df3740?, 0xc001a150b0?, 0x455292?}, {0xc0026952a8?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc0026952a8?, 0xc001a150b0?, 0xc0016ac100?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0025c58c0)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc00129de00, 0xc0025c58c0, 0x2?, 0xc001c04040?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc002595098, 0x1, 0x1?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0xc001df3aa0?, 0xc001a08c00?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc002595080, 0x1, 0xc002203450?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc001df3aa0?, 0xc001a08c00?, 0x455292?}, {0xc002595080?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc002595080?, 0xc001a08c00?, 0xc001533340?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0025c5760)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc0012a9e00, 0xc0025c5760, 0x1?, 0x3a3ed60?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc001a08ab0, 0x2, 0x4?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0x3b9b6e0?, 0xc001a08a50?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc001a08a80, 0x2, 0xc002203420?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0x3b9b6e0?, 0xc001a08a50?, 0x455292?}, {0xc001a08a80?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc001a08a80?, 0xc001a08a50?, 0xc0015332e0?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0025c5600)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc001592780, 0xc0025c5600, 0x0?, 0x3a3ed60?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.call.func9(0xc0024e6370)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1442 +0x8f9\ngithub.com/traefik/yaegi/interp.runCfg(0xc001560640, 0xc0024e6370, 0x0?, 0x45ac520?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc0019fe600, 0x2, 0x4?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\ngithub.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)\n\tgithub.com/traefik/yaegi@v0.15.0/stdlib/go1_19_net_http.go:290\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000245840, {0x52e0cb0, 0xc000efd410}, 0x3c520c0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0026d0000, {0x52e0cb0, 0xc000efd410}, 0xc001b27e00)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc001673b80?, {0x52e0cb0?, 0xc000efd410?}, 0x3a38aa0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000c9c940, {0x52e0cb0, 0xc000efd410}, 0xc00012c960?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/traefik/traefik/v2/pkg/middlewares/snicheck.SNICheck.ServeHTTP({{0x52a6460?, 0xc000c9c940?}, 0xc0019f3500?}, {0x52e0cb0, 0xc000efd410}, 0xc001b27e00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/snicheck/snicheck.go:49 +0x189\ngithub.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4108c7?, {0x52e0cb0, 0xc000efd410}, 0x529ca01?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x62\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc000efd950, {0x52e0cb0, 0xc000efd410}, 0xc001b27d00, 0xc000d6ab80)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x30e\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x52e0cb0?, 0xc000efd410?}, 0xc0019fe450?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:89 +0x68\nnet/http.HandlerFunc.ServeHTTP(0xc000ee8f50?, {0x52e0cb0?, 0xc000efd410?}, 0x9?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000ee8f50, {0x52e0cb0, 0xc000efd410}, 0xc001b27d00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:192 +0xca\nnet/http.AllowQuerySemicolons.func1({0x52e0cb0, 0xc000efd410}, 0xc001b27d00)\n\tnet/http/server.go:2974 +0x223\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x52e0cb0?, 0xc000efd410?}, 0x5?)\n\tnet/http/server.go:2109 +0x2f\nnet/http.serverHandler.ServeHTTP({0x689740?}, {0x52e0cb0, 0xc000efd410}, 0xc001b27d00)\n\tnet/http/server.go:2947 +0x30c\nnet/http.initALPNRequest.ServeHTTP({{0x52ed490?, 0xc0019f6150?}, 0xc000962700?, {0xc0010ae5a0?}}, {0x52e0cb0, 0xc000efd410}, 0xc001b27d00)\n\tnet/http/server.go:3556 +0x245\ngolang.org/x/net/http2.(*serverConn).runHandler(0x7e6a3b8?, 0x0?, 0x0?, 0xc002235680?)\n\tgolang.org/x/net@v0.7.0/http2/server.go:2311 +0x83\ncreated by golang.org/x/net/http2.(*serverConn).processHeaders\n\tgolang.org/x/net@v0.7.0/http2/server.go:2025 +0x64a\n" middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/request.go:50:2: panic" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth
time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/bind.go:61:5: panic" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth
time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/vendor/github.com/go-ldap/ldap/v3/bind.go:100:3: panic" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/ldapauth.go:232:5: panic" plugin=plugin-ldapAuth module=github.com/wiltonsr/ldapAuth
time="2023-03-17T12:44:34Z" level=error msg="plugins-storage/sources/gop-3195890994/src/github.com/wiltonsr/ldapAuth/ldapauth.go:125:6: panic" module=github.com/wiltonsr/ldapAuth plugin=plugin-ldapAuth
time="2023-03-17T12:44:34Z" level=error msg="Recovered from panic in HTTP handler [192.168.32.1:59358 - /favicon.ico]: reflect: Call using int64 as type string" middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2023-03-17T12:44:34Z" level=error msg="Stack: goroutine 106 [running]:\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x52e0cb0, 0xc0014cb238}, 0xc002229a00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x225\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b\npanic({0x3a3ed60, 0xc002024400})\n\truntime/panic.go:884 +0x212\nreflect.Value.call({0x3b06380?, 0xc001a327b0?, 0xc0016afa20?}, {0x472a1fe, 0x4}, {0xc001a327e0, 0x2, 0xc00182f718?})\n\treflect/value.go:440 +0x1abf\nreflect.Value.Call({0x3b06380?, 0xc001a327b0?, 0xc001efd900?}, {0xc001a327e0?, 0xc00182f718?, 0x196?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc001a327e0?, 0xc001a327b0?, 0xc001533c00?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0027b3550)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc001efa280, 0xc0027b3550, 0x2?, 0xc001b95b80?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc0027f4840, 0x1, 0x1?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0xc001df3740?, 0xc001a29b30?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc0027f4828, 0x1, 0xc00229aa90?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc001df3740?, 0xc001a29b30?, 0x455292?}, {0xc0027f4828?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc0027f4828?, 0xc001a29b30?, 0xc0016ac100?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc002753e40)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc00129de00, 0xc002753e40, 0x2?, 0xc001c04040?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc002750618, 0x1, 0x1?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0xc001df3aa0?, 0xc001a1d830?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc002750600, 0x1, 0xc002203450?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc001df3aa0?, 0xc001a1d830?, 0x455292?}, {0xc002750600?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc002750600?, 0xc001a1d830?, 0xc001533340?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc002753ce0)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc0012a9e00, 0xc002753ce0, 0x1?, 0x3a3ed60?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc001a1d6e0, 0x2, 0x4?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\nreflect.Value.call({0x3b9b6e0?, 0xc001a1d680?, 0x41057f?}, {0x472a1fe, 0x4}, {0xc001a1d6b0, 0x2, 0xc002203420?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0x3b9b6e0?, 0xc001a1d680?, 0x455292?}, {0xc001a1d6b0?, 0x46c6b00?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc001a1d6b0?, 0xc001a1d680?, 0xc0015332e0?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1301 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc002753b80)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1326 +0x1265\ngithub.com/traefik/yaegi/interp.runCfg(0xc001592780, 0xc002753b80, 0x0?, 0x3a3ed60?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.call.func9(0xc002712fd0)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1442 +0x8f9\ngithub.com/traefik/yaegi/interp.runCfg(0xc001560640, 0xc002712fd0, 0x0?, 0x45ac520?)\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:213 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc001a17bf0, 0x2, 0x4?})\n\tgithub.com/traefik/yaegi@v0.15.0/interp/run.go:1015 +0x4a5\ngithub.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)\n\tgithub.com/traefik/yaegi@v0.15.0/stdlib/go1_19_net_http.go:290\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000245840, {0x52e0cb0, 0xc0014cb238}, 0x3c520c0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0026d0000, {0x52e0cb0, 0xc0014cb238}, 0xc002229a00)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc0016bb6c0?, {0x52e0cb0?, 0xc0014cb238?}, 0x3a38aa0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000c9c940, {0x52e0cb0, 0xc0014cb238}, 0x0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/traefik/traefik/v2/pkg/middlewares/snicheck.SNICheck.ServeHTTP({{0x52a6460?, 0xc000c9c940?}, 0xc0019f3500?}, {0x52e0cb0, 0xc0014cb238}, 0xc002229a00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/snicheck/snicheck.go:49 +0x189\ngithub.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4108c7?, {0x52e0cb0, 0xc0014cb238}, 0x529ca01?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x62\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc000efd950, {0x52e0cb0, 0xc0014cb238}, 0xc002229800, 0xc001741b80)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x30e\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x52e0cb0?, 0xc0014cb238?}, 0xc001a17aa0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:89 +0x68\nnet/http.HandlerFunc.ServeHTTP(0xc000ee8f50?, {0x52e0cb0?, 0xc0014cb238?}, 0x9?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000ee8f50, {0x52e0cb0, 0xc0014cb238}, 0xc002229800)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:192 +0xca\nnet/http.AllowQuerySemicolons.func1({0x52e0cb0, 0xc0014cb238}, 0xc002229800)\n\tnet/http/server.go:2974 +0x223\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x52e0cb0?, 0xc0014cb238?}, 0xc001f1de08?)\n\tnet/http/server.go:2109 +0x2f\nnet/http.serverHandler.ServeHTTP({0x689740?}, {0x52e0cb0, 0xc0014cb238}, 0xc002229800)\n\tnet/http/server.go:2947 +0x30c\nnet/http.initALPNRequest.ServeHTTP({{0x52ed490?, 0xc0019f6150?}, 0xc000962700?, {0xc0010ae5a0?}}, {0x52e0cb0, 0xc0014cb238}, 0xc002229800)\n\tnet/http/server.go:3556 +0x245\ngolang.org/x/net/http2.(*serverConn).runHandler(0x8b2032?, 0x7e6a3b8?, 0x56bf2a?, 0xc002230001?)\n\tgolang.org/x/net@v0.7.0/http2/server.go:2311 +0x83\ncreated by golang.org/x/net/http2.(*serverConn).processHeaders\n\tgolang.org/x/net@v0.7.0/http2/server.go:2025 +0x64a\n" middlewareName=traefik-internal-recovery middlewareType=Recovery
```

**Comment by wiltonsr** [comment]
Relate to #25
